import{useEffect}from'react';
import{loadSave}from'../core/save.js';
const BOSS='.enemy.boss,.retro-enemy.boss,.future-enemy.boss,.space-enemy.boss,.rift-enemy.boss';
function era(node){if(node.classList.contains('retro-enemy'))return'retro';if(node.classList.contains('future-enemy'))return'future';if(node.classList.contains('space-enemy'))return'space';if(node.classList.contains('rift-enemy'))return'rift';return'stone'}
function fallbackName(node){const title=node.getAttribute('title')||'';if(title)return title.split(/\s+\d+\//)[0].trim();const named=node.dataset.chronoEntityName;if(named)return named;return node.classList.contains('rift-enemy')?'Temporal Boss':'Boss Threat'}
function haptic(pattern=[24,28,38]){try{if(loadSave().settings?.haptics!==false&&typeof navigator?.vibrate==='function')navigator.vibrate(pattern)}catch{}}
function announce(node){if(node.dataset.chronoBossAnnounced==='true')return;node.dataset.chronoBossAnnounced='true';setTimeout(()=>{if(!node.isConnected)return;const t=era(node),name=node.dataset.chronoEntityName||fallbackName(node),banner=document.createElement('div');banner.className=`chrono-boss-entry ${t}`;banner.setAttribute('role','alert');banner.setAttribute('aria-live','assertive');banner.innerHTML=`<div class="chrono-boss-entry-backdrop"></div><section><small>${t==='rift'?'TIMELINE COLLAPSE DETECTED':'BOSS THREAT DETECTED'}</small><b>${name}</b><span>${t==='stone'?'The tribe braces for impact.':t==='retro'?'INSERT COURAGE. CONTINUE?':t==='future'?'Priority hostile entering defense grid.':t==='space'?'Massive hostile entering orbital range.':'Reality is destabilizing.'}</span></section>`;document.body.appendChild(banner);document.body.classList.add('chrono-boss-entering');haptic();setTimeout(()=>document.body.classList.remove('chrono-boss-entering'),520);setTimeout(()=>banner.remove(),1900)},60)}
function phaseAlert(phase){const existing=document.querySelector('.chrono-rift-phase-alert');existing?.remove();const n=document.createElement('div'),name=phase===3?'DEVOURER':'PARADOX',copy=phase===3?'Regeneration surging. The timeline is failing.':'Armor and speed increased. Reality is folding.';n.className=`chrono-rift-phase-alert phase-${phase}`;n.setAttribute('role','alert');n.innerHTML=`<small>CHRONOPHAGE PHASE ${phase}</small><b>${name}</b><span>${copy}</span>`;document.body.appendChild(n);haptic(phase===3?[35,24,35,24,55]:[28,22,42]);setTimeout(()=>n.remove(),1700)}
export function BossEntranceBridge(){useEffect(()=>{document.querySelectorAll(BOSS).forEach(announce);let lastPhase=0,currentHud=null;const scanPhase=()=>{const hud=currentHud;if(!hud||!hud.isConnected){lastPhase=0;return}const p=hud.classList.contains('phase-3')?3:hud.classList.contains('phase-2')?2:1;if(p>lastPhase&&p>=2)phaseAlert(p);lastPhase=p};const phaseObserver=new MutationObserver(scanPhase);const syncHud=()=>{const next=document.querySelector('.chronophage-hud');if(next===currentHud)return;phaseObserver.disconnect();currentHud=next;lastPhase=0;if(currentHud){phaseObserver.observe(currentHud,{attributes:true,attributeFilter:['class']});scanPhase()}};const childObserver=new MutationObserver(records=>{records.forEach(r=>r.addedNodes.forEach(n=>{if(!(n instanceof Element))return;if(n.matches?.(BOSS))announce(n);n.querySelectorAll?.(BOSS).forEach(announce)}));syncHud()});childObserver.observe(document.body,{subtree:true,childList:true});syncHud();return()=>{childObserver.disconnect();phaseObserver.disconnect();document.querySelectorAll('.chrono-boss-entry,.chrono-rift-phase-alert').forEach(n=>n.remove());document.body.classList.remove('chrono-boss-entering')}},[]);return null}
