import React,{useMemo,useState}from'react';
import{chronicleAchievements,chronoRank,unlockedChronicleAchievements}from'../data/chronicleAchievements.js';
const eraInfo=[
 ['stone-age','🪨','Stone Age',25,'totems',75],['retro','🕹️','Retro',25,'cartridges',75],['future','🤖','Future',25,'dataCores',75],['space','🚀','Space',25,'starCores',75],['time-rift','🌀','Time Rift',12,'riftShards',36]
];
export function ChronoProfile({save,onClose,onSwitch}){
 const[tab,setTab]=useState('timeline');
 const rows=useMemo(()=>eraInfo.map(([id,icon,name,maps,reward,maxReward])=>{const world=save.worlds?.[id]??{},unlocked=id==='stone-age'||Boolean(world.unlocked),completed=world.completedMap??0;return{id,icon,name,maps,reward,maxReward,world,unlocked,completed}}),[save]);
 const completed=rows.reduce((n,r)=>n+r.completed,0),total=rows.reduce((n,r)=>n+r.maps,0),awards=rows.reduce((n,r)=>n+(r.world[r.reward]??0),0),maxAwards=rows.reduce((n,r)=>n+r.maxReward,0),mastery=rows.reduce((n,r)=>n+(r.world.mastery??0),0);
 const earned=useMemo(()=>unlockedChronicleAchievements(save),[save]);const earnedIds=useMemo(()=>new Set(earned.map(a=>a.id)),[earned]);const rank=useMemo(()=>chronoRank(save),[save]);
 return <div className="chrono-profile-overlay" onClick={onClose}><div className="chrono-profile" onClick={e=>e.stopPropagation()}>
  <header><div><small>PLAYER CHRONICLE</small><h2>Chrono Defense Timeline</h2><p>{rank.title} • Rank {rank.score}/100</p></div><button onClick={onClose}>×</button></header>
  <div className="chrono-profile-summary"><span><b>{completed}/{total}</b><small>Maps Sealed</small></span><span><b>{awards}/{maxAwards}</b><small>Era Awards</small></span><span><b>{mastery}/500</b><small>Total Mastery</small></span><span><b>{earned.length}/{chronicleAchievements.length}</b><small>Chronicle Feats</small></span></div>
  <nav className="chrono-profile-tabs"><button className={tab==='timeline'?'active':''} onClick={()=>setTab('timeline')}>Timeline</button><button className={tab==='feats'?'active':''} onClick={()=>setTab('feats')}>Chronicle Feats</button></nav>
  {tab==='timeline'?<main>{rows.map(row=><article key={row.id} className={`${row.unlocked?'unlocked':'locked'}`}><div className="profile-era-icon">{row.unlocked?row.icon:'🔒'}</div><div className="profile-era-copy"><small>{row.unlocked?'TIMELINE ACTIVE':'UNKNOWN TIMELINE'}</small><h3>{row.unlocked?row.name:'???'}</h3><div className="profile-bars"><label>Campaign <i><b style={{width:`${row.completed/row.maps*100}%`}}/></i><em>{row.completed}/{row.maps}</em></label><label>Mastery <i><b style={{width:`${row.world.mastery??0}%`}}/></i><em>{row.world.mastery??0}/100</em></label><label>Awards <i><b style={{width:`${(row.world[row.reward]??0)/row.maxReward*100}%`}}/></i><em>{row.world[row.reward]??0}/{row.maxReward}</em></label></div><p>{row.unlocked?`${row.world[row.reward]??0}/${row.maxReward} collectibles earned.`:'Complete the previous era to discover this timeline.'}</p></div>{row.unlocked&&<button onClick={()=>{onSwitch(row.id);onClose()}}>Enter →</button>}</article>)}</main>:<div className="chrono-feat-grid">{chronicleAchievements.map(item=>{const unlocked=earnedIds.has(item.id);return <article key={item.id} className={unlocked?'unlocked':'locked'}><span>{unlocked?item.icon:'?'}</span><div><small>{unlocked?'CHRONICLE FEAT':'UNDISCOVERED'}</small><b>{unlocked?item.name:'Hidden Feat'}</b><p>{unlocked?item.description:'Keep exploring the timeline to reveal this feat.'}</p></div></article>})}</div>}
  <footer><span>{completed===total?'🏆 All known timelines complete.':'⏳ The timeline is still unfolding.'}</span><b>{rank.title}</b></footer>
 </div></div>
}
