import{useEffect}from'react';
import{assetPath}from'../core/assets.js';
import{stoneAgeTowers}from'../data/worlds/stoneAge/towers.js';import{stoneAgeEnemies}from'../data/worlds/stoneAge/enemies.js';import{stoneAgeBosses}from'../data/worlds/stoneAge/bosses.js';import{resourceStructures}from'../data/worlds/stoneAge/resourceStructures.js';
import{retroTowers}from'../data/worlds/retro/towers.js';import{futureTowers}from'../data/worlds/future/towers.js';import{spaceTowers}from'../data/worlds/space/towers.js';import{riftTowers}from'../data/worlds/timeRift/towers.js';import{retroEnemies}from'../data/worlds/retro/enemies.js';import{futureEnemies}from'../data/worlds/future/enemies.js';import{spaceEnemies}from'../data/worlds/space/enemies.js';import{retroBosses}from'../data/worlds/retro/bosses.js';import{futureBosses}from'../data/worlds/future/bosses.js';import{spaceBosses}from'../data/worlds/space/bosses.js';
const worlds=[
{id:'stone-age',towerSelector:'.tower-grid .tower-card',towerHost:'.tower-icon',boardSelector:'.cell.occupied>.placed-icon',enemySelector:'.enemy>span',enemyParent:'.enemy',structureSelector:'.economy-grid .economy-card',structureHost:':scope > span',towers:stoneAgeTowers,structures:resourceStructures,enemies:stoneAgeEnemies,bosses:stoneAgeBosses,titleIdentity:true},
{id:'retro',towerSelector:'.retro-tower-grid button',towerHost:':scope > span',boardSelector:'.retro-cell.occupied>span',enemySelector:'.retro-enemy>span',enemyParent:'.retro-enemy',towers:retroTowers,structures:[],enemies:retroEnemies,bosses:retroBosses},
{id:'future',towerSelector:'.future-towers button',towerHost:':scope > span',boardSelector:'.future-cell.occupied>span',enemySelector:'.future-enemy>span',enemyParent:'.future-enemy',towers:futureTowers,structures:[],enemies:futureEnemies,bosses:futureBosses},
{id:'space',towerSelector:'.space-towers button',towerHost:':scope > span',boardSelector:'.space-cell.occupied>span',enemySelector:'.space-enemy>span',enemyParent:'.space-enemy',towers:spaceTowers,structures:[],enemies:spaceEnemies,bosses:spaceBosses},
{id:'time-rift',towerSelector:'.rift-towers button',towerHost:':scope > span',boardSelector:'.rift-cell.occupied>span',enemySelector:null,towers:riftTowers,structures:[],enemies:[],bosses:[]}
];
function uniqueIconMap(items){const counts=new Map();items.forEach(item=>counts.set(item.icon,(counts.get(item.icon)??0)+1));return new Map(items.filter(item=>counts.get(item.icon)===1).map(item=>[item.icon,item]));}
function rawIcon(host){return[...host.childNodes].find(node=>node.nodeType===Node.TEXT_NODE)?.textContent?.trim()||host.textContent.trim();}
function mountSprite(host,world,kind,id){if(!host||host.dataset.assetBridge===`${world}:${kind}:${id}`)return;host.dataset.assetBridge=`${world}:${kind}:${id}`;const fallback=rawIcon(host);const img=document.createElement('img');img.className='live-asset-sprite';img.alt='';img.draggable=false;img.src=assetPath(world,kind,id);img.addEventListener('load',()=>{host.dataset.assetLoaded='true';host.classList.add('has-live-asset')},{once:true});img.addEventListener('error',()=>{img.remove();host.classList.remove('has-live-asset');host.dataset.assetLoaded='false';if(!rawIcon(host))host.prepend(document.createTextNode(fallback))},{once:true});host.prepend(img);}
function findByTitle(config,parent,isBoss){const title=parent?.getAttribute('title')??'';const list=isBoss?config.bosses:config.enemies;return list.find(item=>title.startsWith(item.name))??null;}
function tagTowerHost(host,config,item,kind='tower'){if(!host||!item)return;const cell=host.closest('.cell,.retro-cell,.future-cell,.space-cell,.rift-cell');if(cell){cell.dataset.chronoEra=config.id;cell.dataset.chronoTowerId=item.id;cell.dataset.chronoTowerName=item.name;cell.dataset.chronoTowerKind=kind;}}
function tagEntity(parent,config,item,isBoss){if(!parent||!item)return;parent.dataset.chronoEra=config.id;parent.dataset.chronoEntityId=item.id;parent.dataset.chronoEntityName=item.name;parent.dataset.chronoEntityKind=isBoss?'boss':'enemy';}
function enhanceWorld(config){const byName=new Map(config.towers.map(item=>[item.name,item])),structuresByName=new Map(config.structures.map(item=>[item.name,item])),towerIcons=uniqueIconMap(config.towers);document.querySelectorAll(config.towerSelector).forEach(button=>{const item=byName.get(button.querySelector('b')?.textContent?.trim()),host=button.querySelector(config.towerHost);if(item&&host){mountSprite(host,config.id,'towers',item.id);button.dataset.chronoTowerId=item.id;button.dataset.chronoEra=config.id}});if(config.structureSelector)document.querySelectorAll(config.structureSelector).forEach(button=>{const item=structuresByName.get(button.querySelector('b')?.textContent?.trim()),host=button.querySelector(config.structureHost);if(item&&host){mountSprite(host,config.id,'structures',item.id);button.dataset.chronoTowerId=item.id;button.dataset.chronoEra=config.id}});document.querySelectorAll(config.boardSelector).forEach(host=>{const title=host.getAttribute('title')?.trim(),namedTower=title?byName.get(title):null,namedStructure=title?structuresByName.get(title):null,icon=rawIcon(host),tower=namedTower??towerIcons.get(icon),structure=namedStructure??config.structures.find(item=>item.icon===icon);if(tower){mountSprite(host,config.id,'towers',tower.id);tagTowerHost(host,config,tower,'tower')}else if(structure){mountSprite(host,config.id,'structures',structure.id);tagTowerHost(host,config,structure,'structure')}});if(config.enemySelector){const enemies=uniqueIconMap(config.enemies),bosses=uniqueIconMap(config.bosses);document.querySelectorAll(config.enemySelector).forEach(host=>{const parent=host.closest(config.enemyParent),isBoss=parent?.classList.contains('boss');const item=config.titleIdentity?findByTitle(config,parent,isBoss):(isBoss?bosses:enemies).get(rawIcon(host));if(item){mountSprite(host,config.id,isBoss?'bosses':'enemies',item.id);tagEntity(parent,config,item,isBoss)}})}}
export function LiveAssetBridge(){useEffect(()=>{let raf=0;const run=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>worlds.forEach(enhanceWorld))};const observer=new MutationObserver(run);observer.observe(document.body,{subtree:true,childList:true});run();return()=>{cancelAnimationFrame(raf);observer.disconnect()}},[]);return null;}
