import{useEffect}from'react';
import{resetBattleMetrics,updateBattleMetrics,getBattleMetrics,markBattleWon}from'../core/battleMetrics.js';
import{evaluateMapObjectives,objectiveLabels}from'../core/mapObjectives.js';
import{stoneAgeMaps}from'../data/worlds/stoneAge/maps.js';import{retroMaps}from'../data/worlds/retro/maps.js';import{futureMaps}from'../data/worlds/future/maps.js';import{spaceMaps}from'../data/worlds/space/maps.js';import{riftMaps}from'../data/worlds/timeRift/maps.js';
import{stoneAgeTowers}from'../data/worlds/stoneAge/towers.js';import{retroTowers}from'../data/worlds/retro/towers.js';import{futureTowers}from'../data/worlds/future/towers.js';import{spaceTowers}from'../data/worlds/space/towers.js';import{riftTowers}from'../data/worlds/timeRift/towers.js';

const configs=[
 {id:'stone-age',root:'.game-frame.battle-screen.enhanced-battle',maps:stoneAgeMaps,towers:stoneAgeTowers,enemy:'.enemy',result:'.result-overlay',map(root){const m=root.querySelector('.brand span')?.textContent.match(/Map\s+(\d+)/);return Number(m?.[1]??1)}},
 {id:'retro',root:'.retro-battle',maps:retroMaps,towers:retroTowers,enemy:'.retro-enemy',result:'.retro-result'},
 {id:'future',root:'.future-battle',maps:futureMaps,towers:futureTowers,enemy:'.future-enemy',result:'.future-result'},
 {id:'space',root:'.space-battle',maps:spaceMaps,towers:spaceTowers,enemy:'.space-enemy',result:'.space-result'},
 {id:'time-rift',root:'.rift-battle',maps:riftMaps,towers:riftTowers,enemy:'.rift-enemy',result:'.rift-result'},
];
function active(){for(const c of configs){const root=document.querySelector(c.root);if(root){let n=c.map?.(root);if(!n){const title=root.querySelector('header b')?.textContent??'';n=c.maps.find(m=>title.includes(m.name))?.number??1}return{c,root,mapNumber:n}}}return null}
function nums(text,re){const m=text.match(re);return m?m.slice(1).map(Number):null}
function health(c,text){if(c.id==='stone-age'){const m=nums(text,/🏕️\s*(\d+)\s*\/\s*(\d+)/);return m?{effective:m[0],primary:m[0],max:m[1]}:null}if(c.id==='retro'){const m=nums(text,/❤️\s*(\d+)\s*•\s*(\d+)\s*\/\s*(\d+)/);return m?{effective:m[0]*m[2]+m[1],primary:m[1],max:(m[0]+1)*m[2],lives:m[0]}:null}if(c.id==='future'){const s=nums(text,/🛡️\s*(\d+)\s*\/\s*(\d+)/),v=nums(text,/💙\s*(\d+)\s*\/\s*(\d+)/);return s&&v?{effective:v[0]*10000+s[0],primary:v[0],max:v[1]*10000+s[1],shield:s[0],core:v[0]}:null}if(c.id==='space'){const s=nums(text,/🛡️\s*(\d+)\s*\/\s*(\d+)/),v=nums(text,/🏙️\s*(\d+)\s*\/\s*(\d+)/);return s&&v?{effective:v[0]*10000+s[0],primary:v[0],max:v[1]*10000+s[1],shield:s[0],colony:v[0]}:null}const m=nums(text,/🧭\s*(\d+)\s*\/\s*(\d+)/);return m?{effective:m[0],primary:m[0],max:m[1],stability:m[0]}:null}
function resources(c,text){if(c.id==='stone-age'){const w=text.match(/🪵\s*(\d+)/),s=text.match(/🪨\s*(\d+)/),f=text.match(/🍖\s*(\d+)/);return{wood:+(w?.[1]??0),stone:+(s?.[1]??0),food:+(f?.[1]??0)}}if(c.id==='retro')return{currency:+(text.match(/🪙\s*(\d+)/)?.[1]??0)};if(c.id==='future')return{currency:+(text.match(/₡\s*(\d+)/)?.[1]??0)};if(c.id==='space')return{currency:+(text.match(/◆\s*(\d+)/)?.[1]??0)};return{currency:+(text.match(/◇\s*(\d+)/)?.[1]??0)}}
function power(text){const m=text.match(/⚡\s*(\d+)\s*\/\s*(\d+)/);return m?Number(m[2])-Number(m[1]):0}
function ensurePanel(root,c,mapNumber){const host=root.querySelector('.board-wrap,.retro-board-wrap,.future-board-wrap,.space-board-wrap,.rift-board-wrap');if(!host)return null;let p=host.querySelector(':scope > .map-objective-tracker');if(!p){p=document.createElement('div');p.className=`map-objective-tracker ${c.id}`;host.appendChild(p)}p.dataset.map=String(mapNumber);return p}
function renderPanel(root,c,mapNumber,m){const panel=ensurePanel(root,c,mapNumber);if(!panel)return;const result=evaluateMapObjectives(c.id,mapNumber,m),labels=objectiveLabels(c.id,mapNumber),state=result.items.map(item=>item.met?'1':'0').join('');if(panel.dataset.state===state)return;panel.dataset.state=state;panel.innerHTML=`<small>MAP OBJECTIVES</small>${labels.map((label,i)=>`<span class="${result.items[i]?.met?'met':''}"><i>${result.items[i]?.met?'✓':i+1}</i>${label}</span>`).join('')}`}
export function MapObjectiveBridge(){useEffect(()=>{let session='',previousResource={},previousHealth=null,seenTowers=new Set(),seenStructures=new Set(),usedRoles=new Set(),eras=new Set(),maxCombat=0,sold=false,actions=0,resourceGain={wood:0,stone:0,food:0},lastEntityHealth=new WeakMap(),lastEntityId=new WeakMap(),winnerMarked=false;const barObservers=new Map();
 const clearBars=()=>{barObservers.forEach(observer=>observer.disconnect());barObservers.clear()};
 const reset=(c,mapNumber,text)=>{clearBars();session=`${c.id}:${mapNumber}`;resetBattleMetrics(c.id,mapNumber);previousResource=resources(c,text);previousHealth=health(c,text)?.effective??null;seenTowers=new Set();seenStructures=new Set();usedRoles=new Set();eras=new Set();maxCombat=0;sold=false;actions=0;resourceGain={wood:0,stone:0,food:0};winnerMarked=false};
 const click=e=>{const found=active();if(!found)return;const b=e.target?.closest?.('button');if(!b)return;const t=(b.textContent??'').trim();if(/^Sell$/i.test(t))sold=true;if(b.closest('.environment-action-bar')&&!b.disabled)actions++};document.addEventListener('click',click,true);
 const watchBar=bar=>{if(!(bar instanceof Element)||barObservers.has(bar))return;const observer=new MutationObserver(()=>{const found=active(),enemy=bar.closest(found?.c?.enemy??'.__none__');if(!found||!enemy)return;const v=parseFloat(bar.style.width||'100');lastEntityHealth.set(enemy,v);lastEntityId.set(enemy,enemy.dataset.chronoEntityId||enemy.dataset.chronoEntityName||'unknown')});observer.observe(bar,{attributes:true,attributeFilter:['style']});barObservers.set(bar,observer)};
 const barsWithin=node=>{if(!(node instanceof Element))return[];const found=active();if(!found)return[];const out=[];if(node.matches?.(`${found.c.enemy} i b`))out.push(node);node.querySelectorAll?.(`${found.c.enemy} i b`).forEach(bar=>out.push(bar));return out};
 const enemiesWithin=(node,selector)=>{if(!(node instanceof Element))return[];return node.matches?.(selector)?[node]:[...node.querySelectorAll?.(selector)??[]]};
 const registerCurrent=()=>{const found=active();if(found)found.root.querySelectorAll(`${found.c.enemy} i b`).forEach(watchBar)};registerCurrent();
 const treeObserver=new MutationObserver(records=>{const found=active();if(!found)return;for(const r of records){r.addedNodes.forEach(n=>barsWithin(n).forEach(watchBar));r.removedNodes.forEach(n=>{barsWithin(n).forEach(bar=>{barObservers.get(bar)?.disconnect();barObservers.delete(bar)});enemiesWithin(n,found.c.enemy).forEach(e=>{if(found.root.querySelector(found.c.result))return;const h=lastEntityHealth.get(e),id=lastEntityId.get(e)||e.dataset.chronoEntityId||e.dataset.chronoEntityName;if(h==null||!id)return;const m=getBattleMetrics(found.c.id,found.mapNumber);if(h<=1.2)updateBattleMetrics(found.c.id,found.mapNumber,{kills:(m.kills??0)+1,killedEntityIds:[...(m.killedEntityIds??[]),id],bossDefeated:Boolean(m.bossDefeated||e.classList.contains('boss'))});else updateBattleMetrics(found.c.id,found.mapNumber,{leaks:(m.leaks??0)+1,leakedEntityIds:[...(m.leakedEntityIds??[]),id]})})})}});treeObserver.observe(document.body,{subtree:true,childList:true});
 const timer=setInterval(()=>{const found=active();if(!found){if(session){session='';clearBars()}return}const{c,root,mapNumber}=found,text=root.textContent,key=`${c.id}:${mapNumber}`;if(key!==session){reset(c,mapNumber,text);registerCurrent()}const cells=[...root.querySelectorAll('[data-chrono-tower-id]')].filter(el=>el.matches('.cell,.retro-cell,.future-cell,.space-cell,.rift-cell')),combat=cells.filter(x=>x.dataset.chronoTowerKind!=='structure'),structures=cells.filter(x=>x.dataset.chronoTowerKind==='structure');combat.forEach(x=>{const id=x.dataset.chronoTowerId;if(!id)return;seenTowers.add(id);const tower=c.towers.find(t=>t.id===id);if(tower?.role)usedRoles.add(tower.role);if(tower?.era)eras.add(tower.era)});structures.forEach(x=>x.dataset.chronoTowerId&&seenStructures.add(x.dataset.chronoTowerId));maxCombat=Math.max(maxCombat,combat.length);const h=health(c,text),res=resources(c,text);if(h&&previousHealth!=null&&h.effective<previousHealth){const m=getBattleMetrics(c.id,mapNumber);updateBattleMetrics(c.id,mapNumber,{leaks:(m.leaks??0)+1})}if(h)previousHealth=h.effective;if(c.id==='stone-age'){for(const k of ['wood','stone','food'])if(res[k]>Number(previousResource[k]??res[k]))resourceGain[k]+=res[k]-Number(previousResource[k]??res[k]);previousResource=res}const combo=Number(text.match(/🔥\s*x\d+\s*\((\d+)\)/)?.[1]??1),m0=getBattleMetrics(c.id,mapNumber),patch={sold,environmentActions:actions,maxCombatTowers:maxCombat,uniqueTowerIds:[...seenTowers],usedTowerIds:[...seenTowers],uniqueStructureIds:[...seenStructures],usedRoles:[...usedRoles],erasUsed:[...eras],resourcesCollected:resourceGain,endingResources:c.id==='stone-age'?res:{},endingCurrency:res.currency??0,bestCombo:Math.max(m0.bestCombo??1,combo),powerFree:c.id==='future'?power(text):(m0.powerFree??0)};if(h)Object.assign(patch,{primaryHealth:h.primary,minPrimaryHealth:Math.min(Number.isFinite(m0.minPrimaryHealth)?m0.minPrimaryHealth:h.primary,h.primary),lives:h.lives??m0.lives,shield:h.shield??m0.shield,core:h.core??m0.core,colony:h.colony??m0.colony,stability:h.stability??m0.stability,maxPrimaryHealth:h.max});const result=root.querySelector(c.result);if(result&&!winnerMarked){const rt=result.textContent.toLowerCase(),won=rt.includes('victory')||rt.includes('clear')||rt.includes('secure')||rt.includes('saved')||rt.includes('stable')||rt.includes('sealed')||rt.includes('complete');if(won){winnerMarked=true;markBattleWon(c.id,mapNumber);patch.won=true;patch.bossDefeated=Boolean(m0.bossDefeated||c.maps[mapNumber-1]?.boss)}}updateBattleMetrics(c.id,mapNumber,patch);renderPanel(root,c,mapNumber,getBattleMetrics(c.id,mapNumber))},220);return()=>{clearInterval(timer);treeObserver.disconnect();clearBars();document.removeEventListener('click',click,true);document.querySelectorAll('.map-objective-tracker').forEach(n=>n.remove())}},[]);return null}
