import{useEffect}from'react';
const CONFIGS=[
 {id:'retro',root:'.retro-battle',board:'.retro-board',cell:'.retro-cell.selected',panel:'.retro-selected-tower'},
 {id:'future',root:'.future-battle',board:'.future-board',cell:'.future-cell.selected',panel:'.future-selected-tower'},
 {id:'space',root:'.space-battle',board:'.space-board',cell:'.space-cell.selected',panel:'.space-selected-tower'},
 {id:'rift',root:'.rift-battle',board:'.rift-board',cell:'.rift-cell.selected',panel:'.rift-selected-tower'},
];
function active(){for(const config of CONFIGS){const root=document.querySelector(config.root);if(root)return{config,root}}return null}
function rangeFrom(panel){const text=panel?.textContent??'';const match=text.match(/RNG\s*(\d+(?:\.\d+)?)/i)||text.match(/RANGE\s*(\d+(?:\.\d+)?)/i);return Number(match?.[1]??0)}
export function RangePreviewBridge(){useEffect(()=>{let last='';const timer=setInterval(()=>{const found=active();if(!found){last='';document.querySelectorAll('.chrono-range-preview').forEach(n=>n.remove());return}const{config,root}=found,board=root.querySelector(config.board),cell=root.querySelector(config.cell),panel=root.querySelector(config.panel),range=rangeFrom(panel);let ring=board?.querySelector(':scope > .chrono-range-preview');if(!board||!cell||!range){ring?.remove();last='';return}const boardRect=board.getBoundingClientRect(),cellRect=cell.getBoundingClientRect(),size=Math.max(22,(range*2/1200)*boardRect.width),left=cellRect.left-boardRect.left+cellRect.width/2,top=cellRect.top-boardRect.top+cellRect.height/2,key=`${config.id}:${Math.round(range)}:${Math.round(size)}:${Math.round(left)}:${Math.round(top)}`;if(key===last&&ring)return;last=key;if(!ring){ring=document.createElement('div');ring.className=`chrono-range-preview ${config.id}`;board.appendChild(ring)}ring.style.width=`${size}px`;ring.style.height=`${size}px`;ring.style.left=`${left}px`;ring.style.top=`${top}px`;ring.title=`Range ${Math.round(range)}`},260);return()=>{clearInterval(timer);document.querySelectorAll('.chrono-range-preview').forEach(n=>n.remove())}},[]);return null}
