import React,{useEffect,useMemo,useRef,useState}from'react';
import{retroTowers}from'../data/worlds/retro/towers.js';
import{retroMaps}from'../data/worlds/retro/maps.js';
import{buildRetroWave,summarizeRetroWave,RETRO_WAVES}from'../data/worlds/retro/waves.js';
import{getRetroLayout,retroCellCenter}from'../data/worlds/retro/layouts.js';
import{distance}from'../core/combat.js';

const CELLS=Array.from({length:60},(_,i)=>i);const START_COINS=450;const MAX_HP=100;
function pathLength(path){let total=0;for(let i=0;i<path.length-1;i++)total+=distance(retroCellCenter(path[i]),retroCellCenter(path[i+1]));return total}
function pointAlong(path,travel){const pts=path.map(retroCellCenter);let left=Math.max(0,travel),total=pathLength(path);for(let i=0;i<pts.length-1;i++){const len=distance(pts[i],pts[i+1]);if(left<=len){const t=left/len;return{x:pts[i].x+(pts[i+1].x-pts[i].x)*t,y:pts[i].y+(pts[i+1].y-pts[i].y)*t,progress:Math.min(1,travel/total)}}left-=len}return{...pts.at(-1),progress:1}}
function unlockedTowers(completed=0){const count=Math.min(retroTowers.length,2+Math.floor(completed/2));return new Set(retroTowers.slice(0,count).map(t=>t.id))}
function towerStats(base,level=1){return{damage:Math.round(base.damage*(1+(level-1)*.42)),range:Math.round(base.range*(1+(level-1)*.07)),fireRate:Math.max(.25,base.fireRate*(1-(level-1)*.09))}}
function upgradeCost(base,level){return Math.round(base.cost*(level===2?.72:1.08))}
function comboMultiplier(combo){if(combo>=40)return5;if(combo>=25)return4;if(combo>=15)return3;if(combo>=7)return2;return1}

export function RetroBattle({mapNumber,save,setSave,onExit,onNextMap}){
 const retro=save.worlds.retro;const map=retroMaps[mapNumber-1];const layout=useMemo(()=>getRetroLayout(mapNumber),[mapNumber]);const pathSet=useMemo(()=>new Set(layout.path),[layout]);const total=useMemo(()=>pathLength(layout.path),[layout]);const unlocked=useMemo(()=>unlockedTowers(retro.completedMap),[retro.completedMap]);
 const[coins,setCoins]=useState(START_COINS);const[lives,setLives]=useState(3);const[baseHp,setBaseHp]=useState(MAX_HP);const[wave,setWave]=useState(1);const[selected,setSelected]=useState('pixel-blaster');const[placed,setPlaced]=useState({});const[selectedCell,setSelectedCell]=useState(null);const[enemies,setEnemies]=useState([]);const[running,setRunning]=useState(false);const[paused,setPaused]=useState(false);const[speed,setSpeed]=useState(1);const[combo,setCombo]=useState(1);const[score,setScore]=useState(0);const[message,setMessage]=useState('Build your arcade defenses, then start Wave 1.');const[status,setStatus]=useState('ready');
 const coinsRef=useRef(coins),placedRef=useRef(placed),enemiesRef=useRef(enemies),runningRef=useRef(running),pausedRef=useRef(paused),waveRef=useRef(wave),comboRef=useRef(combo),scoreRef=useRef(score),livesRef=useRef(lives),hpRef=useRef(baseHp);const queueRef=useRef([]),cooldowns=useRef({}),finalized=useRef(false),killsRef=useRef(0);
 const syncCoins=v=>{coinsRef.current=v;setCoins(v)},syncPlaced=v=>{placedRef.current=v;setPlaced(v)},syncEnemies=v=>{enemiesRef.current=v;setEnemies(v)},syncRun=v=>{runningRef.current=v;setRunning(v)},syncCombo=v=>{comboRef.current=v;setCombo(v)},syncScore=v=>{scoreRef.current=v;setScore(v)},syncLives=v=>{livesRef.current=v;setLives(v)},syncHp=v=>{hpRef.current=v;setBaseHp(v)};
 useEffect(()=>{pausedRef.current=paused},[paused]);useEffect(()=>{waveRef.current=wave},[wave]);
 const preview=useMemo(()=>summarizeRetroWave(buildRetroWave({mapNumber,waveNumber:wave})).slice(0,5),[mapNumber,wave]);
 const complete=()=>{if(finalized.current)return;finalized.current=true;syncRun(false);setStatus('won');const cartridges=1+(livesRef.current>=2?1:0)+(comboRef.current>=12?1:0);setSave(prev=>{const old=prev.worlds.retro;const prior=old.best?.[map.id]?.cartridges??0;const added=Math.max(0,cartridges-prior);const nextRetro={...old,completedMap:Math.max(old.completedMap??0,mapNumber),highestMap:Math.min(25,Math.max(old.highestMap??1,mapNumber<25?mapNumber+1:25)),cartridges:Math.min(75,(old.cartridges??0)+added),mastery:Math.min(100,(old.mastery??0)+2+Math.floor(killsRef.current/25)),highScore:Math.max(old.highScore??0,scoreRef.current),bestCombo:Math.max(old.bestCombo??1,comboRef.current),best:{...(old.best??{}),[map.id]:{cartridges:Math.max(prior,cartridges),score:scoreRef.current,combo:comboRef.current,lives:livesRef.current}}};const next={...prev,worlds:{...prev.worlds,retro:nextRetro}};if(mapNumber===25)next.worlds.future={...next.worlds.future,unlocked:true};return next});setMessage(`CLEAR! ${cartridges}/3 cartridges • Score ${scoreRef.current.toLocaleString()}`)};
 const fail=()=>{if(finalized.current)return;finalized.current=true;syncRun(false);setStatus('lost');queueRef.current=[];setSave(prev=>{const old=prev.worlds.retro;return{...prev,worlds:{...prev.worlds,retro:{...old,highScore:Math.max(old.highScore??0,scoreRef.current),bestCombo:Math.max(old.bestCombo??1,comboRef.current)}}}});setMessage('GAME OVER — the cabinet was overwhelmed.')};
 const finishWave=()=>{syncRun(false);if(waveRef.current>=RETRO_WAVES){complete();return}const next=waveRef.current+1;waveRef.current=next;setWave(next);syncCoins(coinsRef.current+50+next*8);setMessage(`Wave clear! Bonus coins awarded. Build before Wave ${next}.`)};
 const startWave=()=>{if(runningRef.current||finalized.current)return;const units=buildRetroWave({mapNumber,waveNumber:waveRef.current});queueRef.current=units.map((u,i)=>({...u,uid:`r-${Date.now()}-${i}`,delay:i*520,travel:0,x:retroCellCenter(layout.path[0]).x,y:retroCellCenter(layout.path[0]).y,dead:false,phaseClock:0}));syncRun(true);setStatus('running');setMessage(units.some(u=>u.boss)?`👑 ${units.find(u=>u.boss).name} HAS ENTERED THE GAME`:`Wave ${waveRef.current} — GO!`)};
 const place=cell=>{if(runningRef.current||pathSet.has(cell))return;if(placedRef.current[cell]){setSelectedCell(cell);return}const tower=retroTowers.find(t=>t.id===selected);if(!tower||!unlocked.has(tower.id)||coinsRef.current<tower.cost)return;syncCoins(coinsRef.current-tower.cost);syncPlaced({...placedRef.current,[cell]:{id:tower.id,level:1,invested:tower.cost,targeting:'first'}});setSelectedCell(cell)};
 const upgrade=()=>{const p=placedRef.current[selectedCell],base=retroTowers.find(t=>t.id===p?.id);if(!p||!base||p.level>=3)return;const cost=upgradeCost(base,p.level+1);if(coinsRef.current<cost)return;syncCoins(coinsRef.current-cost);syncPlaced({...placedRef.current,[selectedCell]:{...p,level:p.level+1,invested:p.invested+cost}})};
 const sell=()=>{const p=placedRef.current[selectedCell];if(!p)return;syncCoins(coinsRef.current+Math.round(p.invested*.65));const next={...placedRef.current};delete next[selectedCell];syncPlaced(next);setSelectedCell(null)};
 useEffect(()=>{const timer=setInterval(()=>{if(!runningRef.current||pausedRef.current)return;const dt=.05*speed;const spawn=[],wait=[];queueRef.current.forEach(e=>{const d=e.delay-dt*1000;(d<=0?spawn:wait).push(d<=0?{...e,delay:0}:{...e,delay:d})});queueRef.current=wait;let active=[...enemiesRef.current.map(e=>({...e})),...spawn];active.forEach(e=>{let mult=1;if(e.erratic)mult*=.8+Math.random()*.45;if(e.phase){e.phaseClock=(e.phaseClock??0)+dt;e.untargetable=Math.sin(e.phaseClock*3)> .82}e.travel+=e.speed*mult*dt;const pos=pointAlong(layout.path,e.travel);e.x=pos.x;e.y=pos.y;e.progress=pos.progress});
  for(const[cell,p]of Object.entries(placedRef.current)){const base=retroTowers.find(t=>t.id===p.id);if(!base||base.damage<=0)continue;const key=String(cell);cooldowns.current[key]=(cooldowns.current[key]??0)-dt;if(cooldowns.current[key]>0)continue;const stats=towerStats(base,p.level),origin=retroCellCenter(Number(cell));let candidates=active.filter(e=>!e.dead&&!e.untargetable&&distance(origin,e)<=stats.range);if(!candidates.length)continue;candidates.sort((a,b)=>b.progress-a.progress);const target=candidates[0];let damage=Math.max(1,Math.round(stats.damage*(1-Math.min(.78,target.armor??0))));if(base.id==='boss-buster'&&target.boss)damage=Math.round(damage*2.2);if(base.id==='tesla-coil'){[target,...candidates.slice(1,3)].forEach((e,i)=>{e.hp-=Math.round(damage*(1-i*.22));e.lastHitTower=base.id;if(e.hp<=0)e.dead=true})}else if(base.id==='boom-box'||base.id==='missile-command'){active.filter(e=>!e.dead&&distance(e,target)<90).forEach(e=>{e.hp-=damage;e.lastHitTower=base.id;if(e.hp<=0)e.dead=true})}else{target.hp-=damage;target.lastHitTower=base.id;if(base.id==='freeze-ray')target.speed=Math.max(18,target.speed*.96);if(base.id==='glitch-tower')target.speed=Math.max(16,target.speed*.94);if(target.hp<=0)target.dead=true}cooldowns.current[key]=stats.fireRate}
  let lostHp=hpRef.current,lostLives=livesRef.current,killed=0,earned=0;const survivors=[];active.forEach(e=>{if(e.dead||e.hp<=0){killed++;const mult=comboMultiplier(comboRef.current);earned+=Math.round((e.coinReward??5)*mult);syncScore(scoreRef.current+Math.round((e.coinReward??5)*100*mult));syncCombo(Math.min(99,comboRef.current+1));return}if(e.travel>=total){let dmg=e.baseDamage??10;if(e.stealsCoins)syncCoins(Math.max(0,coinsRef.current-75));lostHp-=dmg;syncCombo(1);while(lostHp<=0&&lostLives>0){lostLives--;lostHp+=MAX_HP}return}survivors.push(e)});if(killed){killsRef.current+=killed;syncCoins(coinsRef.current+earned)}syncHp(Math.max(0,lostHp));syncLives(lostLives);syncEnemies(survivors);if(lostLives<=0){fail();return}if(queueRef.current.length===0&&survivors.length===0)finishWave()},50);return()=>clearInterval(timer)},[layout,total,speed,mapNumber]);
 const selectedData=selectedCell!=null?placed[selectedCell]:null,selectedBase=selectedData?retroTowers.find(t=>t.id===selectedData.id):null;
 return <section className="retro-battle"><header className="retro-battle-hud"><div><b>🕹️ {map.name}</b><small>{map.zone}</small></div><div className="retro-hud-values"><span>🪙 {coins}</span><span>❤️ {lives} • {baseHp}/{MAX_HP}</span><span>🔥 x{comboMultiplier(combo)} <small>({combo})</small></span><span>🏆 {score.toLocaleString()}</span><span>🌊 {wave}/{RETRO_WAVES}</span></div><div><button onClick={onExit} disabled={running}>⌂</button><button onClick={()=>setPaused(v=>!v)} disabled={!running}>{paused?'▶':'⏸'}</button><button onClick={()=>setSpeed(v=>v===1?2:v===2?3:1)}>{speed}×</button><button className="retro-start" onClick={startWave} disabled={running||finalized.current}>START {wave}</button></div></header>
 <div className="retro-battle-body"><div className="retro-board-wrap"><div className="retro-preview"><b>{message}</b><span>{preview.map(item=>`${item.name} ×${item.count}`).join(' • ')}</span></div><div className="retro-board">{CELLS.map(cell=>{const p=placed[cell],base=p?retroTowers.find(t=>t.id===p.id):null;return <button key={cell} className={`retro-cell ${pathSet.has(cell)?'path':''} ${layout.bonusPads.includes(cell)?'bonus':''} ${p?'occupied':''} ${selectedCell===cell?'selected':''}`} onClick={()=>place(cell)}>{base?<span>{base.icon}<small>{p.level>1?`L${p.level}`:''}</small></span>:pathSet.has(cell)?'·':layout.bonusPads.includes(cell)?'⭐':''}</button>})}{enemies.map(e=><div key={e.uid} className={`retro-enemy ${e.boss?'boss':''} ${e.untargetable?'phased':''}`} style={{left:`${e.x/12}%`,top:`${e.y/5}%`}}><span>{e.boss?e.icon:e.icon}</span><i><b style={{width:`${Math.max(0,e.hp/e.maxHp*100)}%`}}/></i></div>)}</div></div>
 <aside className="retro-build"><h3>DEFENSE SELECT</h3><div className="retro-tower-grid">{retroTowers.map(t=>{const locked=!unlocked.has(t.id);return <button key={t.id} disabled={locked} className={selected===t.id?'selected':''} onClick={()=>setSelected(t.id)}><span>{t.icon}</span><div><b>{t.name}</b><small>{locked?'LOCKED':t.role}</small></div><em>🪙{t.cost}</em></button>})}</div>{selectedBase?<div className="retro-selected-tower"><b>{selectedBase.icon} {selectedBase.name}</b><span>Level {selectedData.level}</span><small>{(()=>{const s=towerStats(selectedBase,selectedData.level);return`DMG ${s.damage} • RNG ${s.range}`})()}</small><div><button onClick={upgrade} disabled={selectedData.level>=3}>Upgrade</button><button onClick={sell}>Sell</button></div></div>:<div className="retro-tip">Fast kills build Combo. Higher Combo multiplies coin rewards and score.</div>}</aside></div>
 {(status==='won'||status==='lost')&&<div className="retro-result"><div><strong>{status==='won'?'STAGE CLEAR':'GAME OVER'}</strong><h2>{message}</h2><p>Score {score.toLocaleString()} • Best combo {combo}</p><button onClick={onExit}>Campaign</button>{status==='won'&&mapNumber<25&&<button onClick={()=>onNextMap(mapNumber+1)}>Next Cabinet →</button>}</div></div>}</section>;
}
