import React,{useMemo,useState}from'react';
import{retroTowers}from'../data/worlds/retro/towers.js';
import{retroEnemies}from'../data/worlds/retro/enemies.js';
import{retroBosses}from'../data/worlds/retro/bosses.js';
import{retroUnlockedTowerIds}from'../data/worlds/retro/unlocks.js';
import{AssetSprite}from'./AssetSprite.jsx';
const tabs=[['towers','🕹️ Towers'],['enemies','👾 Enemies'],['bosses','👑 Bosses']];
function traits(e){const out=[];if(e.phase)out.push('Phasing');if(e.split)out.push('Splits');if(e.stealsCoins)out.push('Coin Thief');if(e.disrupt)out.push('Disruptor');if(e.shield)out.push('Shielded');if(e.erratic)out.push('Erratic');if((e.armor??0)>=.4)out.push('Heavy Armor');return out;}
export function RetroCodex({retroSave,onClose}){const[tab,setTab]=useState('towers');const unlocked=useMemo(()=>retroUnlockedTowerIds(retroSave),[retroSave]);return <div className="retro-codex-overlay" onClick={onClose}><div className="retro-codex" onClick={e=>e.stopPropagation()}><header><div><small>ARCADE DATABASE</small><h2>Retro Field Guide</h2></div><button onClick={onClose}>×</button></header><nav>{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><main>{tab==='towers'&&<div className="retro-codex-grid">{retroTowers.map(t=>{const open=unlocked.has(t.id);return <article key={t.id} className={open?'':'locked'}><div className="retro-codex-icon">{open?<AssetSprite world="retro" kind="towers" id={t.id} fallback={t.icon} alt={t.name}/>:<span>🔒</span>}</div><div><small>{t.role}</small><h3>{open?t.name:'???'}</h3>{open&&<><p>🪙{t.cost} • DMG {t.damage} • RNG {t.range}</p><span><b>{t.branchA}</b> — {t.branchADescription}</span><span><b>{t.branchB}</b> — {t.branchBDescription}</span></>}</div></article>})}</div>}{tab==='enemies'&&<div className="retro-codex-grid compact">{retroEnemies.map(e=><article key={e.id}><div className="retro-codex-icon"><AssetSprite world="retro" kind="enemies" id={e.id} fallback={e.icon} alt={e.name}/></div><div><small>TIER {e.tier}</small><h3>{e.name}</h3><p>HP {e.hp} • SPD {e.speed} • ARM {Math.round(e.armor*100)}%</p><div className="retro-traits">{(traits(e).length?traits(e):['Basic']).map(x=><em key={x}>{x}</em>)}</div></div></article>)}</div>}{tab==='bosses'&&<div className="retro-codex-grid bosses">{retroBosses.map(b=><article key={b.id}><div className="retro-codex-icon"><AssetSprite world="retro" kind="bosses" id={b.id} fallback={b.icon} alt={b.name}/></div><div><small>MAP {b.map} BOSS</small><h3>{b.name}</h3><p>HP {b.hp.toLocaleString()} • ARM {Math.round(b.armor*100)}%</p><strong>{b.mechanic}</strong></div></article>)}</div>}</main></div></div>}
