import{useEffect}from'react';
const configs=[
 {root:'.retro-battle',cards:'.retro-tower-grid button',currency:/🪙\s*(\d+)/,cost:/🪙\s*(\d+)/,label:'coins'},
 {root:'.future-battle',cards:'.future-towers button',currency:/₡\s*(\d+)/,cost:/₡\s*(\d+)/,label:'credits'},
 {root:'.space-battle',cards:'.space-towers button',currency:/◆\s*(\d+)/,cost:/◆\s*(\d+)/,label:'Matter'},
 {root:'.rift-battle',cards:'.rift-towers button',currency:/◇\s*(\d+)/,cost:/◇\s*(\d+)/,label:'Chronons'}
];
function refresh(){let handled=false;for(const c of configs){const root=document.querySelector(c.root);if(!root)continue;handled=true;const money=+(root.textContent.match(c.currency)?.[1]??0);root.querySelectorAll(c.cards).forEach(card=>{card.classList.remove('chrono-affordable','chrono-too-expensive','chrono-locked');const locked=card.disabled||/LOCKED/i.test(card.textContent);const cost=+(card.textContent.match(c.cost)?.[1]??0);if(locked){card.classList.add('chrono-locked');if(!card.title)card.title='Locked. Continue this era to unlock.';return}if(card.classList.contains('no-power')){card.title='Insufficient Power capacity. Build grid support first.';return}if(cost>money){card.classList.add('chrono-too-expensive');card.title=`Need ${Math.max(0,cost-money)} more ${c.label}.`}else{card.classList.add('chrono-affordable');if(card.title?.startsWith('Need '))card.removeAttribute('title')}});break}if(!handled)document.querySelectorAll('.tower-card').forEach(card=>{card.classList.toggle('chrono-too-expensive',Boolean(card.querySelector('.cost.poor')));card.classList.toggle('chrono-affordable',!card.disabled&&!card.querySelector('.cost.poor'));if(card.disabled)card.classList.add('chrono-locked');else card.classList.remove('chrono-locked')})}
export function ShopAffordabilityBridge(){useEffect(()=>{const timer=setInterval(refresh,280);refresh();return()=>{clearInterval(timer);document.querySelectorAll('.chrono-affordable,.chrono-too-expensive,.chrono-locked').forEach(n=>n.classList.remove('chrono-affordable','chrono-too-expensive','chrono-locked'))}},[]);return null}
