import{stoneAgeMaps}from'../data/worlds/stoneAge/maps.js';
import{retroMaps}from'../data/worlds/retro/maps.js';
import{futureMaps}from'../data/worlds/future/maps.js';
import{spaceMaps}from'../data/worlds/space/maps.js';
import{riftMaps}from'../data/worlds/timeRift/maps.js';

const configs={
 'stone-age':{maps:stoneAgeMaps,rewardKey:'totems',mapRecordKey:'totems',max:75},
 retro:{maps:retroMaps,rewardKey:'cartridges',mapRecordKey:'cartridges',max:75},
 future:{maps:futureMaps,rewardKey:'dataCores',mapRecordKey:'dataCores',max:75},
 space:{maps:spaceMaps,rewardKey:'starCores',mapRecordKey:'starCores',max:75},
 'time-rift':{maps:riftMaps,rewardKey:'riftShards',mapRecordKey:'shards',max:36},
};
const has=(arr,id)=>Array.isArray(arr)&&arr.includes(id);
const any=(arr,ids)=>ids.some(id=>has(arr,id));
const noLeakOf=(m,parts)=>!(m.leakedEntityIds??[]).some(id=>parts.some(part=>String(id).includes(part)));
function labels(worldId,map){if(worldId==='stone-age')return['Complete the map',map.number%2?'Village stays above 75%':'Take no village damage',map.bonusObjective];if(worldId==='retro')return map.cartridges;if(worldId==='future')return map.dataCores;if(worldId==='space')return map.starCores;return map.shards;}
function stoneSpecial(n,m){switch(n){case 1:return m.maxCombatTowers<=6;case 2:return(m.uniqueStructureIds?.length??0)>=1;case 3:return(m.primaryHealth??0)>=225;case 4:return(m.resourcesCollected?.food??0)>=100;case 5:case 10:case 15:case 20:case 25:return Boolean(m.bossDefeated||m.won);case 6:return(m.uniqueTowerIds?.length??0)>=3;case 7:return!m.sold;case 8:return(m.leaks??0)===0;case 9:return['wood-camp','quarry','hunter-camp'].every(id=>has(m.uniqueStructureIds,id));case 11:return(m.primaryHealth??0)>=188;case 12:return(m.kills??0)>=75;case 13:return m.maxCombatTowers<=8;case 14:return noLeakOf(m,['mammoth']);case 16:return(m.endingResources?.stone??0)>=50;case 17:return any(m.usedTowerIds??[],['fire-keeper','fire-slinger']);case 18:return(m.environmentActions??0)>=1;case 19:return(m.uniqueTowerIds?.length??0)<=5;case 21:return(m.kills??0)>=100;case 22:return(m.usedRoles??[]).some(r=>/support|buff|debuff/i.test(r));case 23:return['wood','stone','food'].every(k=>(m.endingResources?.[k]??0)>=25);case 24:return(m.leaks??0)===0;default:return Boolean(m.won)}}
function retroSpecial(n,m){switch(n){case 1:case 2:case 3:case 6:case 9:case 11:case 12:case 14:case 19:case 21:case 22:case 24:return(m.leaks??0)===0;case 4:return(m.bestCombo??1)>=10;case 5:case 10:case 15:case 20:case 25:return Boolean(m.bossDefeated||m.won);case 7:return noLeakOf(m,['ghost']);case 8:return noLeakOf(m,['coin-thief','thief']);case 13:return noLeakOf(m,['block','tank','armor']);case 16:return(m.bestCombo??1)>=20;case 17:return noLeakOf(m,['virus']);case 18:return(m.endingCurrency??0)>=500;case 23:return(m.lives??0)>=3;default:return Boolean(m.won)}}
function evaluate(worldId,mapNumber,m={}){const cfg=configs[worldId],map=cfg?.maps?.[mapNumber-1];if(!map)return{count:0,items:[]};let tests=[];if(worldId==='stone-age'){tests=[Boolean(m.won),mapNumber%2?(m.primaryHealth??0)>=188:(m.leaks??0)===0,stoneSpecial(mapNumber,m)];}else if(worldId==='retro'){tests=[Boolean(m.won),mapNumber%2?(m.lives??0)>=2:(m.bestCombo??1)>=12,retroSpecial(mapNumber,m)];}else if(worldId==='future'){tests=[Boolean(m.won),(m.core??0)>=150,mapNumber%3?(m.powerFree??-1)>0:has(m.usedTowerIds,'fusion-reactor')];}else if(worldId==='space'){tests=[Boolean(m.won),(m.colony??0)>=75,mapNumber%2?(m.shield??0)>0:any(m.usedTowerIds??[],['gravity-well','tractor-beam'])];}else{tests=[Boolean(m.won),(m.stability??0)>=700,mapNumber%2?(m.erasUsed?.length??0)>=3:(m.uniqueTowerIds?.length??0)>=4];}const ls=labels(worldId,map);const items=ls.map((label,i)=>({label,met:Boolean(tests[i])}));return{count:items.filter(x=>x.met).length,items,map,cfg};}
export function evaluateMapObjectives(worldId,mapNumber,metrics={}){return evaluate(worldId,mapNumber,metrics)}
export function objectiveConfig(worldId){return configs[worldId]??null}
export function objectiveLabels(worldId,mapNumber){const cfg=configs[worldId],map=cfg?.maps?.[mapNumber-1];return map?labels(worldId,map):[]}
export function correctObjectiveRewards({beforeWorld={},afterWorld={},worldId,mapNumber,metrics={}}){const result=evaluate(worldId,mapNumber,metrics),cfg=configs[worldId];if(!cfg||!result.map||!metrics.won)return{world:afterWorld,result};const mapId=result.map.id,priorRecord=beforeWorld.best?.[mapId]??{},afterRecord=afterWorld.best?.[mapId]??{},prior=Number(priorRecord[cfg.mapRecordKey]??0),generic=Number(afterRecord[cfg.mapRecordKey]??prior),genericAdded=Math.max(0,generic-prior),desired=Math.max(prior,result.count),desiredAdded=Math.max(0,desired-prior),total=Math.max(0,Math.min(cfg.max,Number(afterWorld[cfg.rewardKey]??0)-genericAdded+desiredAdded));return{world:{...afterWorld,[cfg.rewardKey]:total,best:{...(afterWorld.best??{}),[mapId]:{...afterRecord,[cfg.mapRecordKey]:desired,objectives:result.items,objectiveComplete:result.items.every(x=>x.met)}}},result};}
